# TODO
# general settings
model_type: SR_l1Model
scale: 2
num_gpu: 6  # set num_gpu: 0 for cpu mode
manual_seed: 10
propotion: 2
# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: data/DIV2K/DIV2K_train_HR_sub
    dataroot_lq: data/DIV2K/DIV2K_train_LR_bicubic/X2_sub
#    dataroot_gt: /home/isalab303/XXX/data/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /home/isalab303/XXX/data/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
#    dataroot_gt: /home/isalab303/XXX/data/benchmark/Set5/GTmod12
#    dataroot_lq: /home/isalab303/XXX/data/benchmark/Set5/LRbicx2
    dataroot_gt: data/Set5/GTmod12
    dataroot_lq: data/Set5/LRbicx2
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: data/Set14/GTmod12
    dataroot_lq: data/Set14/LRbicx2
#    filename_tmpl: '{}x3'
    io_backend:
      type: disk

  val_3:
    name: B100
    type: PairedImageDataset
    dataroot_gt: data/B100/GTmod12
    dataroot_lq: data/B100/LRbicx2
#    filename_tmpl: '{}x3'
    io_backend:
      type: disk

  val_4:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: data/Urban100/GTmod12
    dataroot_lq: data/Urban100/LRbicx2
#    filename_tmpl: '{}x3'
    io_backend:
      type: disk
# network structures  /home/xiangchuang/glr/basic/experiments/RCANx2_ft2/models/net_g_73500.pth
network_g:
  type: RCAN_sharedup
  n_resgroups: 5
  n_resblocks: 5
  n_feats: 64
  reduction: 16
  scale: 2
  rgb_range: 255
  n_colors: 3
  pretrained: False
  path: ~
  tea: False
  kd: True
  group_id: [0,2,4]

network_t:
  group_id: [0,4,9]
  type: RCAN_sharedup
  n_resgroups: 10
  n_resblocks: 20
  n_feats: 64
  reduction: 16
  scale: 2
  rgb_range: 255
  n_colors: 3
  pretrained: True
  path: /home/glinrui/teacher_checkpoint/net_g_105000.pth
#  path: /home/xiangchuang/glr/teacher_checkpoint/net_g_105000.pth
#  path: /home/glr/teacher_checkpoint/net_g_105000.pth
#  path: /home/isalab305/XXX/teacher_checkpoint/net_g_105000.pth
  tea: True
  kd: True

# path
path:
  pretrain_network_g: ~
  pretrain_network_t: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
#  kd_opt:
#    type: L1Loss
#    loss_weight: 0.33
#    reduction: mean
#  adpat_opt:
#    type: AdaptLoss_nochannel
#    loss_weight: 0.5
#    reduction: mean
  wave_opt:
    type: WaveLoss
    loss_weight: 0.025
    reduction: mean
  adpat_gt_opt:
    type: AdaptLoss_nochannel
    loss_weight: 0.2
    reduction: mean                #adapt同时出现代表 输出用adapt gt   中间用adapt
#  adpat_three_opt:
#    type: AdaptLoss_three
#    loss_weight: 2
#    reduction: mean


saveadapt: True
# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True
    ssim_y:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

# logging settings
name: shareup_kd_saveacf
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e5
  use_tb_logger: true
  wandb:
    project: test-project
    resume_id: ~
    note: shareup_kd_saveacf
    id: shareup_kd_saveacf
#  wandb:
#    project: ~
#    resume_id: ~
#    note: ~
#    id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
