# TODO
# general settings
name: RCANx4_ft_DIV2K_rand0
model_type: SR_ftModel
scale: 4
num_gpu: 6  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
#    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X2_sub
#    dataroot_gt: /home/isalab303/XXX/data/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /home/isalab303/XXX/data/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    dataroot_gt: data/DIV2K/DIV2K_train_HR_sub
    dataroot_lq: data/DIV2K/DIV2K_train_LR_bicubic/X4_sub
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
#    dataroot_gt: /home/isalab303/XXX/data/benchmark/Set5/GTmod12
#    dataroot_lq: /home/isalab303/XXX/data/benchmark/Set5/LRbicx2
    dataroot_gt: data/Set5/GTmod12
    dataroot_lq: data/Set5/LRbicx4
#    dataroot_gt: datasets/Set5/HR
#    dataroot_lq: datasets/Set5/LR_bicubic/X2
    io_backend:
      type: disk

# network structures
network_g:
  type: RCAN_ft
  n_resgroups: 10
  n_resblocks: 20
  n_feats: 64
  reduction: 16
  scale: 4
  rgb_range: 255
  n_colors: 3
  path: RCAN_BIX4.pt
  tea: False
  pretrained: True
  group_percen: 80
path:
  pretrain_network_g: ~
  pretrain_network_t: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [60000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: test-project
#    project: ~
    resume_id: ~
    note: fullupgroup
# dist training settings
dist_params:
  backend: nccl
  port: 29500
