# TODO
# general settings

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: data/DIV2K/DIV2K_train_HR_sub
    dataroot_lq: data/DIV2K/DIV2K_train_LR_bicubic/X4_sub
#    dataroot_gt: /home/isalab303/XXX/data/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /home/isalab303/XXX/data/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
#    dataroot_gt: /home/isalab303/XXX/data/benchmark/Set5/GTmod12
#    dataroot_lq: /home/isalab303/XXX/data/benchmark/Set5/LRbicx2
#    dataroot_gt: data/Set5/GTmod12
#    dataroot_lq: data/Set5/LRbicx2
    dataroot_gt: data/Set5/GTmod12
    dataroot_lq: data/Set5/LRbicx4
    io_backend:
      type: disk

# network structures
network_g:
  type: RCAN_ft2
  n_resgroups: 10
  n_resblocks: 5
  n_feats: 64
  reduction: 16
  scale: 4
  rgb_range: 255

  n_colors: 3
  pretrained: False
  tea: False
  path: ~

network_t:
  type: RCAN_ft2
  n_resgroups: 10
  n_resblocks: 20
  n_feats: 64
  reduction: 16
  scale: 4
  rgb_range: 255
  n_colors: 3
  pretrained: True
  tea: True
  path: rcan_t26_x4.pth
path:
  pretrain_network_t: ~
#  pretrain_network_t: /home/glinrui/basic/checkpoints/rcan_net_g_70000.pth
  strict_load_g: False
  resume_state: ~

# training settings
#sim_w: 0.5
#ada_w: 0.16


train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  sim_opt:
    type: SimLoss
    loss_weight: 1.0
    reduction: mean
  adpat_opt:
    type: AdaptLoss
    loss_weight: 1.0
    reduction: mean
  ada_sim_opt:
    type: Adapt_SIMLoss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: test-project
#    project: ~
    resume_id: ~
    note: a100alladapt
# dist training settings
dist_params:
  backend: nccl
  port: 29500

name: fta_RCANx4_ft_m_DIV2K_rand0
model_type: SR_kd2Model
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
#sim_w: 2
#sim_wt: 5
#ada_w: 0.22222
#ada_wt: 0.66667

#sim_w: 1.4
#sim_wt: 2.8
#ada_w: 0.1444444
#ada_wt: 0.2888889

#sim_w: 0
#sim_wt: 0
#ada_w: 0.1444444
#ada_wt: 0.2888889
#
#sim_w: 2             tea/stu   0.95:0.05不如0.7:0.3
#sim_wt: 8             20000iter    33.9431
#ada_w: 0.4
#ada_wt: 1.6


#sim_w: 8       #5000iter   33.0032
#sim_wt: 16     #65000iter 34.38  比如4.yml
#ada_w: 1.6
#ada_wt: 3.2
#sim_w: 2           #  tea/stu   0.95:0.05不如0.7:0.3
#sim_wt: 8           #  20000iter    33.9431
#ada_w: 0.4           #现在是0.6和0.4
#ada_wt: 1.6
sim_w: 2
sim_wt: 8
ada_w: 80         # alladaptsetting
ada_wt: 320
